
server:
  port: 8085
spring:
  application:
    name: eureka-feign
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
      service-url:
        default-zone: http://localhost:8761/demo/eureka
        defaultZone: http://localhost:8761/demo/eureka
feign:
  hystrix:
    enabled: true